[package]
name = "rusty_web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.21.8"
mio = { version = "0.8", features = ["os-poll", "net"] }
